require 'llvm/core'
require 'llvm/target'
require 'llvm/execution_engine'
require 'llvm/transforms/scalar'

require 'genera/runtime'
require 'genera/context'
require 'genera/prototype'
require 'genera/node'
require 'genera/float'
require 'genera/bool'
require 'genera/int'
require 'genera/function'
require 'genera/math'
