require 'llvm/core'

require 'genera/context'
require 'genera/node'
require 'genera/data'
require 'genera/bool_literal'
require 'genera/int_literal'
require 'genera/float_literal'
require 'genera/cond'
require 'genera/bool_cond'
require 'genera/float_cond'
require 'genera/int_cond'
require 'genera/function'
